/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectivesRouteImport } from './routes/collectives'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsNewRouteImport } from './routes/products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectivesRoute = CollectivesRouteImport.update({
  id: '/collectives',
  path: '/collectives',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collectives': typeof CollectivesRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/enquiries': typeof EnquiriesRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/products/new': typeof ProductsNewRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collectives': typeof CollectivesRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/enquiries': typeof EnquiriesRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/products/new': typeof ProductsNewRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collectives': typeof CollectivesRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/enquiries': typeof EnquiriesRoute
  '/marketing': typeof MarketingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/products/new': typeof ProductsNewRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/collectives'
    | '/dashboard'
    | '/earnings'
    | '/enquiries'
    | '/marketing'
    | '/onboarding'
    | '/profile'
    | '/marketplace/$id'
    | '/products/new'
    | '/marketplace/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/collectives'
    | '/dashboard'
    | '/earnings'
    | '/enquiries'
    | '/marketing'
    | '/onboarding'
    | '/profile'
    | '/marketplace/$id'
    | '/products/new'
    | '/marketplace'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/collectives'
    | '/dashboard'
    | '/earnings'
    | '/enquiries'
    | '/marketing'
    | '/onboarding'
    | '/profile'
    | '/marketplace/$id'
    | '/products/new'
    | '/marketplace/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CollectivesRoute: typeof CollectivesRoute
  DashboardRoute: typeof DashboardRoute
  EarningsRoute: typeof EarningsRoute
  EnquiriesRoute: typeof EnquiriesRoute
  MarketingRoute: typeof MarketingRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectives': {
      id: '/collectives'
      path: '/collectives'
      fullPath: '/collectives'
      preLoaderRoute: typeof CollectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CollectivesRoute: CollectivesRoute,
  DashboardRoute: DashboardRoute,
  EarningsRoute: EarningsRoute,
  EnquiriesRoute: EnquiriesRoute,
  MarketingRoute: MarketingRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
